[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"

[workspace]
members = [
    # The generic hal definitions
    "avr-hal-generic",

    # The chip definitions
    "chips/atmega1280-hal",
    "chips/atmega168-hal",
    "chips/atmega2560-hal",
    "chips/atmega328p-hal",
    "chips/atmega328pb-hal",
    "chips/atmega32u4-hal",
    "chips/atmega48p-hal",
    "chips/attiny85-hal",
    "chips/attiny88-hal",

    # The board crates
    "boards/arduino-diecimila",
    "boards/arduino-leonardo",
    "boards/arduino-uno",
    "boards/arduino-mega2560",
    "boards/bigavr6",
    "boards/sparkfun-pro-micro",
    "boards/trinket",
]

[patch.crates-io]
# XXX: Temporary fix for avr-rust/rust#148
ufmt = { git = "https://github.com/Rahix/ufmt.git", rev = "12225dc1678e42fecb0e8635bf80f501e24817d9" }
