[package]
name = "bigavr6"
version = "0.1.0"
authors = ["Gabriel Pickl <gabriel.pickl@posteo.net>"]
edition = "2018"

[dependencies]
atmega1280-hal = { path = "../../chips/atmega1280-hal/" }
avr-hal-generic = { path = "../../avr-hal-generic/" }

[dev-dependencies]
panic-halt = "0.2.0"
nb = "0.1.2"
