[package]
name = "attiny88-hal"
version = "0.1.0"
authors = ["Andrew Dona-Couch <avr-hal@couchand.com>"]
edition = "2018"

[features]
rt = ["avr-device/rt"]

[dependencies]
avr-hal-generic = { path = "../../avr-hal-generic/" }

[dependencies.avr-device]
version = "0.3"
features = ["attiny88"]
