[general]
board = "micro"

# The Arduino Micro does not have a UART console like other Arduino boards.
# Instead, it can emulate a console device over USB, but this is not yet
# supported in `avr-hal`.  To get console output from an Arduino Micro, you
# need to connect an external usb-serial converter to the TX/RX pins of your
# board.
open-console = false

# For documentation about this file, check here:
# https://github.com/Rahix/avr-hal/blob/main/ravedude/README.md#ravedudetoml-format
