[general]
board = "uno"
serial-baudrate = 57600
open-console = true

# For documentation about this file, check here:
# https://github.com/Rahix/avr-hal/blob/main/ravedude/README.md#ravedudetoml-format
