[package]
name = "trinket-examples"
version = "0.0.0"
authors = ["Jan Paw <jpaw@virtuslab.com>"]
edition = "2021"
publish = false

[dependencies]
panic-halt = "0.2.0"
embedded-hal = "1.0"

[dependencies.embedded-hal-v0]
version = "0.2.3"
package = "embedded-hal"

[dependencies.arduino-hal]
path = "../../arduino-hal/"
features = ["trinket"]

# The latest releases of `proc-macro2` do not support the rust toolchain that
# we use.  Thus, we must fix this dependency to an older version where our
# toolchain is still supported.  See https://github.com/Rahix/avr-hal/issues/537
[build-dependencies.proc-macro2]
version = "=1.0.82"
