[package]
name = "digispark-examples"
version = "0.0.0"
authors = ["Jan Paw <jpaw@virtuslab.com>"]
edition = "2018"
publish = false

[dependencies]
panic-halt = "0.2.0"
embedded-hal = "0.2.3"

[dependencies.arduino-hal]
path = "../../arduino-hal/"
features = ["digispark"]
